### ISSUE TITLE
Incorrect P2 Installer Link under Readme file

### ISSUE THREAD

**Issue by kgera-tibco** [surfra/Tibco#1]
Hi Francesco, 

A link(URL) under Readme is broken which is directing to repo consisting of P2 installed folder. Request you to please update the ReadMe file with below changes:

**https://github.com/surfra/Tibco/tree/master/TibcoUtilities/TibcoBusinessWorks/TibcoUtilities** needs to be changed to **https://github.com/surfra/tci-bw-utilities/tree/master/tibco-bw-utilities/TibcoBusinessWorks/TibcoUtilities**

Thanks,
Karan Gera

**Comment by cohsysops** [comment]
This link is also not working for me.
